# Site
name: 'Bleuciel Market'
description: 'A collection of junk drawings of the one and only Bleuciel!'
logo: 'assets/images/Logo_1_Blau.svg' #logo.png'
favicon: 'assets/images/Logo_1_Blau.svg'
baseurl: ''
avatar: #'assets/images/avatar.png'
email: 'bleuciel.market@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
      
# Syntax
markdown: kramdown
highlighter: rouge

# Pagination
paginate: 100


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
